version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "astro-portabletext"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "demo"
    schedule:
      interval: "weekly"
