name: CI

on:
  push:
    branches:
      - main
      - next

  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16]
      
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Format
        run: pnpm format

      - name: Run Test
        run: pnpm test:ci
   
  dispatch_release:
    name: Dispatch Release
    needs: [test]
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      ref: ${{ github.ref }}
    