name: Release

on:
  repository_dispatch:
    types: [release]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to NPM
        uses: changesets/action@v1
        with:
          commit: '[ci] release'
          title: '[ci] release'
          version: pnpm exec changeset version
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        