name: Release

on:
  repository_dispatch:
    types: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - run: | 
          echo ${{ github.event.client_payload.ref }}
          echo ${{ github.event.client_payload.sha }}
        
